# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('density', models.FloatField(verbose_name='kg/m3')),
            ],
        ),
    ]
